// export const CHAT_USER = "CHAT_USER";
// export const ACTIVE_USER = "ACTIVE_USER";
// export const FULL_USER = "FULL_USER";
// export const ADD_LOGGED_USER = "ADD_LOGGED_USER";
// export const CREATE_GROUP = "CREATE_GROUP";
// export const CREATE_GROUP_REQUEST = "CREATE_GROUP_REQUEST";
// export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
// export const CREATE_GROUP_FAILURE = "CREATE_GROUP_FAILURE";

// export const FETCH_ALL_SERVERS = "FETCH_ALL_SERVERS";
// export const FETCH_ALL_SERVERS_SUCCESS = "FETCH_ALL_SERVERS_SUCCESS";
// export const FETCH_ALL_SERVERS_FAILURE = "FETCH_ALL_SERVERS_FAILURE";




// constants.js
export const ACTIVE_USER = 'ACTIVE_USER';
export const ADD_LOGGED_USER = 'ADD_LOGGED_USER';
export const CHAT_USER = 'CHAT_USER';
export const CREATE_GROUP = 'CREATE_GROUP';
export const CREATE_GROUP_FAILURE = 'CREATE_GROUP_FAILURE';
export const CREATE_GROUP_REQUEST = 'CREATE_GROUP_REQUEST';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';

export const FULL_USER = 'FULL_USER';


// constants.js
export const FETCH_ALL_GROUPS = 'FETCH_ALL_GROUPS';
export const FETCH_ALL_GROUPS_SUCCESS = 'FETCH_ALL_GROUPS_SUCCESS';
export const FETCH_ALL_GROUPS_FAILURE = 'FETCH_ALL_GROUPS_FAILURE';

export const DELETE_GROUP_REQUEST= 'DELETE_GROUP_REQUEST';
export const DELETE_GROUP_SUCCESS= 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_FAILURE= 'DELETE_GROUP_FAILURE';

export const UPDATE_GROUP_REQUEST= 'UPDATE_GROUP_REQUEST';